name: Get Deploy Stage

inputs:
  base-ref:
    required: true
    type: string
# Map the step outputs to action outputs
outputs:
  STAGE:
    description: "The detected stage"
    value: ${{ steps.deploy_info.outputs.STAGE }}

runs:
  using: "composite"
  steps:
    - id: deploy_info
      shell: bash
      run: |
        if [[ $BASE_REF == "master" || $BASE_REF == "main" ]]
        then
            echo "STAGE=prod" >> $GITHUB_OUTPUT
        elif [[ $BASE_REF == "beta" ]]
        then
            echo "STAGE=beta" >> $GITHUB_OUTPUT
        else
            echo "STAGE=dev" >> $GITHUB_OUTPUT
        fi
      env:
        BASE_REF: ${{ inputs.base-ref }}
