name: Build and Deploy 🚀

on:
  pull_request:
    branches: [ dev, beta, master ]
    types: [closed]
  workflow_dispatch:
    inputs:
      stack-glob:
        type: string
        description: Glob to select stacks to deploy
        default: '*'

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get PR Labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6

      - name: Detect Deployment Type
        id: deployment
        run: |
          DEPLOY_ALL=$GITHUB_PR_LABEL_DEPLOY_ALL
          DEPLOY_AFFECTED=$GITHUB_PR_LABEL_DEPLOY_AFFECTED
          if [[ ("$DEPLOY_AFFECTED" -eq "1") && ( ( -z "$DEPLOY_ALL") || ("0" -eq "$DEPLOY_ALL") ) ]]; then
            echo "deployment-type=affected" >> $GITHUB_OUTPUT
            echo "::debug::Deploy: affected"
          else
            echo "deployment-type=all" >> $GITHUB_OUTPUT
            echo "::debug::Deploy: all"
          fi

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.ref }}
          regex: '(refs/heads/)?(.+)'

      - name: Build and Deploy
        uses: ./.github/actions/build-and-run-cdk
        with:
          deployment-type: ${{ steps.deployment.outputs.deployment-type }}
          cdk-subcommand: deploy
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          base-ref: ${{ github.base_ref || format('{0}~1', steps.regex-match.outputs.group2) }}
          stack-glob: ${{ github.event.inputs.stack-glob }}

      - name: Slack Notification
        if: ${{ success() || failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: deploy-bot
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.slack-edge.com/2022-11-24/4406160137991_174b810c603c442d470f_96.png
          SLACK_TITLE: "[${{ github.base_ref || steps.regex-match.outputs.group2 }}] newpet Deploy 🚀"
          SLACK_WEBHOOK: ${{ secrets.DEPLOY_BOT_SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Deployment Type: ${{ steps.deployment.outputs.deployment-type }}"
